# **Modul 2: Data Analysis**
# Exercise Numpy

In [ ]:
# import library
import numpy as np
import pandas as pd

In [ ]:
print(np.__version__)
print(pd.__version__)

1.21.6
1.3.5


In [ ]:
print(np.__version__)
print(pd.__version__)

1.21.6
1.3.5


## **Soal A**

## **No.1**


In [ ]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr_2 = ((10,11,12),(13,14,15),(16,17,8))

arr_np = np.array(arr)
arr_np_2 = np.array(arr_2)

print(arr_np)
print(arr_np_2)

print(f'arr : {type(arr)}, arr_np : {type(arr_np)}')
print(f'arr_2 : {type(arr_2)}, arr_np_2 : {type(arr_np_2)}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17  8]]
arr : <class 'list'>, arr_np : <class 'numpy.ndarray'>
arr_2 : <class 'tuple'>, arr_np_2 : <class 'numpy.ndarray'>


## **No.2**

In [ ]:
np.eye(5) * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

## **No.3**

In [ ]:
np.random.seed(32)

np.random.randint(1,11,20).reshape(5,4)

array([[ 8,  6,  7,  9],
       [ 4,  8, 10,  4],
       [ 6, 10,  5,  2],
       [ 4,  2,  3,  4],
       [ 9,  3,  5,  3]])

## **No.4**

In [ ]:
np.random.seed(101)
arr = np.random.randint(1,10,20)
arr

array([2, 7, 8, 9, 5, 9, 6, 1, 6, 9, 2, 4, 9, 4, 4, 3, 9, 4, 8, 1])

In [ ]:
print(f'Mean : {arr.mean()}')
print(f'Median : {np.median(arr)}')
print(f'Max : {arr.max()}')
print(f'Min : {arr.min()}')
print(f'Max Index : {arr.argmax()}')
print(f'Min Index: {arr.argmin()}')
print(f'Shape: {arr.shape}')

Mean : 5.5
Median : 5.5
Max : 9
Min : 1
Max Index : 3
Min Index: 7
Shape: (20,)


## **No.5**

In [ ]:
x = np.arange(1,21).reshape(5,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [ ]:
x+y

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13, 15, 17, 19],
       [17, 19, 21, 23]])

## Soal B

## **No.6**

1. https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html
1. https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

In [ ]:
# Agar saat generate bilangan random tidak berubah
np.random.seed(2022)

# Buat array 1 dimensi ukuran 36 dengan data random Integer, simpan dalam variabel bernama myArray
myArray = np.random.randint(1,100,36)
myArray

array([93, 46, 50, 56, 89, 19, 25, 17, 54, 42, 34, 28, 12, 20, 95, 76, 49,
       20, 39, 73, 15, 94, 17, 91, 12, 95, 98,  3, 81, 16, 24, 82, 88, 86,
       38, 57])

## **No.7**

1. https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
1. https://fgnt.github.io/python_crashkurs_doc/include/numpy.html

In [ ]:
# Buat 3 Matrix dengan dimensi berbeda
Soal2_1 = myArray.reshape(2,18)
Soal2_2 = myArray.reshape(9,4)
Soal2_3 = myArray.reshape(2,6,3)

print ('\n Matrix 1 :\n', Soal2_1)
print ('\n Matrix 2 :\n', Soal2_2)
print ('\n Array3D 3 :\n', Soal2_3)


 Matrix 1 :
 [[93 46 50 56 89 19 25 17 54 42 34 28 12 20 95 76 49 20]
 [39 73 15 94 17 91 12 95 98  3 81 16 24 82 88 86 38 57]]

 Matrix 2 :
 [[93 46 50 56]
 [89 19 25 17]
 [54 42 34 28]
 [12 20 95 76]
 [49 20 39 73]
 [15 94 17 91]
 [12 95 98  3]
 [81 16 24 82]
 [88 86 38 57]]

 Array3D 3 :
 [[[93 46 50]
  [56 89 19]
  [25 17 54]
  [42 34 28]
  [12 20 95]
  [76 49 20]]

 [[39 73 15]
  [94 17 91]
  [12 95 98]
  [ 3 81 16]
  [24 82 88]
  [86 38 57]]]


## **No.8**

1. https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html
1. https://numpy.org/doc/stable/reference/generated/numpy.ndarray.max.html
1. https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin
1. https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
myArray

array([93, 46, 50, 56, 89, 19, 25, 17, 54, 42, 34, 28, 12, 20, 95, 76, 49,
       20, 39, 73, 15, 94, 17, 91, 12, 95, 98,  3, 81, 16, 24, 82, 88, 86,
       38, 57])

In [ ]:
print(np.amin(myArray))
print(np.amax(myArray))

# Nilai Minimum dan Maksimum
Soal3_Min = myArray.min()
Soal3_Max = myArray.max()

# Index dari Nilai Minimum dan Maksimum
Soal3_ArgMin = myArray.argmin()
Soal3_ArgMax = myArray.argmax()

print (f'Nilai minimun : {Soal3_Min}')
print (f'Nilai maximum : {Soal3_Max}')
print (f'Nilai Minimum ({Soal3_Min}) berada pada Index : {Soal3_ArgMin}')
print (f'Nilai Maximum ({Soal3_Max}) berada pada Index : {Soal3_ArgMax}')

3
98
Nilai minimun : 3
Nilai maximum : 98
Nilai Minimum (3) berada pada Index : 27
Nilai Maximum (98) berada pada Index : 26


In [ ]:
print(myArray.max())
print(np.where(myArray == myArray.max()))

print(myArray.min())
print(np.where(myArray == myArray.min()))


98
(array([26]),)
3
(array([27]),)


## **No.9**

In [ ]:
myArray

array([93, 46, 50, 56, 89, 19, 25, 17, 54, 42, 34, 28, 12, 20, 95, 76, 49,
       20, 39, 73, 15, 94, 17, 91, 12, 95, 98,  3, 81, 16, 24, 82, 88, 86,
       38, 57])

In [ ]:
# Fancy Indexing, dengan double bracket
Soal4 = myArray[[3, 5, 30, 12, 15, 8, 24, 14, 22]]
Soal4

array([56, 19, 24, 12, 76, 54, 12, 95, 17])

In [ ]:
# reshape
Soal_4 = Soal4.reshape(3,3)
Soal_4

array([[56, 19, 24],
       [12, 76, 54],
       [12, 95, 17]])

In [ ]:
new_Array = myArray[np.array([3, 5, 30, 12, 15, 8, 24, 14, 22])].reshape(3,3)
new_Array

array([[56, 19, 24],
       [12, 76, 54],
       [12, 95, 17]])

In [ ]:
Soal4

array([56, 19, 24, 12, 76, 54, 12, 95, 17])

## **No.10**

In [ ]:
myArray

array([93, 46, 50, 56, 89, 19, 25, 17, 54, 42, 34, 28, 12, 20, 95, 76, 49,
       20, 39, 73, 15, 94, 17, 91, 12, 95, 98,  3, 81, 16, 24, 82, 88, 86,
       38, 57])

In [ ]:
Soal_4 > 50
bool_arr = Soal_4 > 50
bool_arr
Soal_4[bool_arr]

array([56, 76, 54, 95])

In [ ]:
# Conditional Statement
Soal5 = Soal4.reshape(3,3)[Soal4.reshape(3,3) > 50]
Soal5

array([56, 76, 54, 95])

In [ ]:
# Conditional Statement
Soal5 = Soal4[Soal4 > 50]
Soal5

array([56, 76, 54, 95])

In [ ]:
Soal4

array([56, 19, 24, 12, 76, 54, 12, 95, 17])

In [ ]:
Soal4 > 50

array([ True, False, False, False,  True,  True, False,  True, False])

In [ ]:
Soal4[[True, False, False, False,  True,  True, False,  True, False]]

array([56, 76, 54, 95])

## **No.11**

1. https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
1. https://numpy.org/doc/stable/reference/generated/numpy.arange.html

In [ ]:
# Linspace
Soal6 = np.linspace(0,100, num=5, dtype=int)
Soal6

array([  0,  25,  50,  75, 100])

In [ ]:
Arr6 = np.linspace(0,100,5, dtype=int)
Arr6


array([  0,  25,  50,  75, 100])

In [ ]:
# Kalau np.arange outputnya integer
np.arange(0,101,25)

array([  0,  25,  50,  75, 100])

## **No.12**

1. https://numpy.org/doc/stable/reference/generated/numpy.ones.html
1. https://numpy.org/doc/stable/reference/generated/numpy.full.html

In [ ]:
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
myArray = [1, 1, 1, 1, 1, 1, 1, 1, 1]
x = np.array(myArray)
N = int(input('N yang diinputkan adalah : '))
x.reshape(N, N)
slice_of_x = x.reshape(N,N)
slice_of_x[:] = 8
slice_of_x

N yang diinputkan adalah : 3


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
# Buat Array Isi 10
N = int(input('Masukkan Nilai N : '))
print (f'N yang diinputkan adalah {N}')

Soal7 = np.ones((N,N))*8
Soal7

Masukkan Nilai N : 3
N yang diinputkan adalah 3


array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [ ]:
np.full((3,3) , 8, dtype=float)

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [ ]:
np.full(shape=(3,3),fill_value=8, dtype=float)

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [ ]:
np.ones((1,3))

array([[1., 1., 1.]])

In [ ]:
n = int(input())
np.full((n,n),8)

3


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.array([['Andi',3, 'Jakarta'],['Budi',7,'Bandung']])

array([['Andi', '3', 'Jakarta'],
       ['Budi', '7', 'Bandung']], dtype='<U21')

## **No.13**

1. https://numpy.org/doc/stable/reference/generated/numpy.transpose.html
1. https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
np.linspace(100,400,4).reshape(4,1)

array([[100.],
       [200.],
       [300.],
       [400.]])

In [ ]:
arrayA = np.arange(1,13).reshape(3,4)
arrayA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arrayB = np.arange(100,401,100).reshape(4,1)
arrayB

array([[100],
       [200],
       [300],
       [400]])

In [ ]:
arrayB.T

array([[100, 200, 300, 400]])

In [ ]:
# gabungkan arrayA dan arrayB
arrayC = np.concatenate((arrayA, arrayB.T), axis=0)
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

In [ ]:
Array3 = np.arange(100,401,100)
Array3
ArrayA = Array3.reshape(4,1)
ArrayA
Array5 = np.arange(1,13)
Array5
Array5 = np.arange(1,13)
Array5
ArrayB = Array5.reshape(3,4)
ArrayB
np.concatenate((ArrayB,ArrayA.T), axis=0)

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

## **No.14**

slicing = [start:stop:step]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[::2] # tidak ada start:tidak ada stop:step nya setiap 2 angka

array([1, 3, 5, 7])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # indexing 0 1 2 3 4 5 6
arr[1:5:2] # start di index 1:stop di index 5:step nya setiap 2 angka

array([2, 4])

In [ ]:
#negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # -7 -6 -5 -4 -3 -2 -1
arr[-3:-1]

array([5, 6])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[4:] # start di index 4:tidak ada stop

array([5, 6, 7])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[1:5] # start di index 1:stop di index 5

array([2, 3, 4, 5])

In [ ]:
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

In [ ]:
# slicing array-> array[row, column]
arrayC[1:3 , 2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]

array([7, 8, 9])

In [ ]:
arr[0:, 2]

array([3, 8])

In [ ]:
arrayD = np.take(arrayC, (6,7,10,11))
arrayD.shape = (2,2)
arrayD


array([[ 7,  8],
       [11, 12]])

## **No.15**

In [ ]:
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

In [ ]:
print(arrayC[3:,1:2])
print(arrayC[3,1:2])

[[200]]
[200]


In [ ]:
display(arrayC[3:,1:2])
display(arrayC[3,1:2])

array([[200]])

array([200])

In [ ]:
# indexing array => [row,column]
arrayC[3, 1]

200

In [ ]:
arrayC[3, 1] / arrayC[3, 0]

2.0

In [ ]:
arrayC[3][1]

200

In [ ]:
np.where(arrayC==200)

(array([3]), array([1]))

## **Test**

In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.full((2,2), 10)


In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
(b)

array([[10, 10],
       [10, 10]])

In [ ]:
print(a+b)
print(np.add(a,b))

[[11 12]
 [13 14]]
[[11 12]
 [13 14]]


In [ ]:
print(a-b)
print(np.subtract(a,b))

[[-9 -8]
 [-7 -6]]
[[-9 -8]
 [-7 -6]]


In [ ]:
print(a*b)
print(np.multiply(a,b))

[[10 20]
 [30 40]]
[[10 20]
 [30 40]]


In [ ]:
print(np.dot(a,b))

[[30 30]
 [70 70]]
